-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.awaria_paczkomatu
(
    id serial NOT NULL,
    data_zgloszenia timestamp(6) without time zone NOT NULL,
    opis text COLLATE pg_catalog."default" NOT NULL,
    status_awarii character varying(20) COLLATE pg_catalog."default" NOT NULL,
    wymaga_blokady boolean NOT NULL,
    paczkomat_id integer NOT NULL,
    zglaszajacy_id integer,
    CONSTRAINT awaria_paczkomatu_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.blokada_paczkomatu
(
    id serial NOT NULL,
    data_blokady timestamp(6) without time zone NOT NULL,
    data_odblokowania timestamp(6) without time zone,
    powod text COLLATE pg_catalog."default",
    awaria_id integer,
    paczkomat_id integer NOT NULL,
    CONSTRAINT blokada_paczkomatu_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.historia_statusu
(
    id serial NOT NULL,
    czas_zmiany timestamp(6) without time zone NOT NULL,
    komentarz text COLLATE pg_catalog."default",
    przesylka_id integer NOT NULL,
    status_id integer NOT NULL,
    uzytkownik_id integer,
    CONSTRAINT historia_statusu_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.paczkomat
(
    id serial NOT NULL,
    adres text COLLATE pg_catalog."default" NOT NULL,
    kod character varying(20) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    sortownia_id integer,
    CONSTRAINT paczkomat_pkey PRIMARY KEY (id),
    CONSTRAINT uk_53eq4shgvimu7i11d6c1jsm2r UNIQUE (kod)
);

CREATE TABLE IF NOT EXISTS public.przesylka
(
    id serial NOT NULL,
    gabaryt character varying(10) COLLATE pg_catalog."default",
    kod_odbioru character varying(20) COLLATE pg_catalog."default" NOT NULL,
    numer character varying(40) COLLATE pg_catalog."default" NOT NULL,
    opis text COLLATE pg_catalog."default",
    waga numeric(8, 2),
    aktualny_status_id integer,
    paczkomat_docelowy_id integer,
    paczkomat_nadania_id integer,
    CONSTRAINT przesylka_pkey PRIMARY KEY (id),
    CONSTRAINT uk_8ig96aj19k1donr9jwc069fte UNIQUE (numer)
);

CREATE TABLE IF NOT EXISTS public.przesylka_zadanie
(
    przesylka_id integer NOT NULL,
    zadanie_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.skrytka
(
    id serial NOT NULL,
    numer character varying(10) COLLATE pg_catalog."default" NOT NULL,
    rozmiar character varying(10) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    paczkomat_id integer NOT NULL,
    CONSTRAINT skrytka_pkey PRIMARY KEY (id),
    CONSTRAINT uk6bncxxpti0682cwjbv9tdht63 UNIQUE (paczkomat_id, numer)
);

CREATE TABLE IF NOT EXISTS public.sortownia
(
    id serial NOT NULL,
    adres text COLLATE pg_catalog."default" NOT NULL,
    nazwa character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sortownia_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.status_przesylki
(
    id serial NOT NULL,
    kod character varying(30) COLLATE pg_catalog."default" NOT NULL,
    opis text COLLATE pg_catalog."default",
    CONSTRAINT status_przesylki_pkey PRIMARY KEY (id),
    CONSTRAINT uk_8e36gmqujtphuqiptrdj6be73 UNIQUE (kod)
);

CREATE TABLE IF NOT EXISTS public.uzytkownik
(
    id serial NOT NULL,
    haslo_hash text COLLATE pg_catalog."default" NOT NULL,
    login character varying(50) COLLATE pg_catalog."default" NOT NULL,
    rola character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT uzytkownik_pkey PRIMARY KEY (id),
    CONSTRAINT uk_jnbal73tjtpy7nt6y3ad6a52q UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS public.zadanie_dystrybucyjne
(
    id serial NOT NULL,
    data_konca timestamp(6) without time zone,
    data_startu timestamp(6) without time zone,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    typ character varying(20) COLLATE pg_catalog."default" NOT NULL,
    kurier_id integer,
    sortownia_id integer,
    CONSTRAINT zadanie_dystrybucyjne_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.zgloszenie_nieprawidlowej_przesylki
(
    id serial NOT NULL,
    data_zgloszenia timestamp(6) without time zone NOT NULL,
    opis text COLLATE pg_catalog."default",
    typ character varying(30) COLLATE pg_catalog."default" NOT NULL,
    przesylka_id integer NOT NULL,
    zglaszajacy_id integer,
    CONSTRAINT zgloszenie_nieprawidlowej_przesylki_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.awaria_paczkomatu
    ADD CONSTRAINT fk3xy6rwh1mmsuwfmi6o7llvjj3 FOREIGN KEY (paczkomat_id)
        REFERENCES public.paczkomat (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.awaria_paczkomatu
    ADD CONSTRAINT fk592htjhxgdfjy9uudjkr7tyfo FOREIGN KEY (zglaszajacy_id)
        REFERENCES public.uzytkownik (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.blokada_paczkomatu
    ADD CONSTRAINT fk6c7g409v6rpogy20130pg5o04 FOREIGN KEY (paczkomat_id)
        REFERENCES public.paczkomat (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.blokada_paczkomatu
    ADD CONSTRAINT fk7co3atdc0kc5w4vbl32kfuuom FOREIGN KEY (awaria_id)
        REFERENCES public.awaria_paczkomatu (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historia_statusu
    ADD CONSTRAINT fk2r18ixj0wj7lp83nd9s0ldnu5 FOREIGN KEY (uzytkownik_id)
        REFERENCES public.uzytkownik (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historia_statusu
    ADD CONSTRAINT fk6susre4st51au05xpnh7c98n0 FOREIGN KEY (przesylka_id)
        REFERENCES public.przesylka (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historia_statusu
    ADD CONSTRAINT fkop7577r6fynbr2wx96l292s83 FOREIGN KEY (status_id)
        REFERENCES public.status_przesylki (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.paczkomat
    ADD CONSTRAINT fkffnnr49wam5y0jpv8ih6enyha FOREIGN KEY (sortownia_id)
        REFERENCES public.sortownia (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.przesylka
    ADD CONSTRAINT fkm3flxejjbgve2o9kte8ijo4c0 FOREIGN KEY (paczkomat_docelowy_id)
        REFERENCES public.paczkomat (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.przesylka
    ADD CONSTRAINT fkpt67nto6emdrh2xix15k753ra FOREIGN KEY (paczkomat_nadania_id)
        REFERENCES public.paczkomat (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.przesylka
    ADD CONSTRAINT fktpl2nl05a1o9iy7r8w98n6qsx FOREIGN KEY (aktualny_status_id)
        REFERENCES public.status_przesylki (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.przesylka_zadanie
    ADD CONSTRAINT fk4oidmod7p4qiha36ehfsecr93 FOREIGN KEY (zadanie_id)
        REFERENCES public.zadanie_dystrybucyjne (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.przesylka_zadanie
    ADD CONSTRAINT fkfn5o0kjmmjscxw9c6r4fbeitc FOREIGN KEY (przesylka_id)
        REFERENCES public.przesylka (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.skrytka
    ADD CONSTRAINT fkl3akxxmeluo69dyrj038o2r0u FOREIGN KEY (paczkomat_id)
        REFERENCES public.paczkomat (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.zadanie_dystrybucyjne
    ADD CONSTRAINT fk14914lcr8i6w0p0u74n7f7d19 FOREIGN KEY (sortownia_id)
        REFERENCES public.sortownia (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.zadanie_dystrybucyjne
    ADD CONSTRAINT fklhjo1m02wivqqq32aakdfyeh2 FOREIGN KEY (kurier_id)
        REFERENCES public.uzytkownik (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.zgloszenie_nieprawidlowej_przesylki
    ADD CONSTRAINT fkib5ntejww8b8d9wqsinj2mipc FOREIGN KEY (przesylka_id)
        REFERENCES public.przesylka (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.zgloszenie_nieprawidlowej_przesylki
    ADD CONSTRAINT fksepe3j3sivlkfsk2vk7m88fkn FOREIGN KEY (zglaszajacy_id)
        REFERENCES public.uzytkownik (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;

END;